PROCEDURE Last_update IS
BEGIN
	begin
	UPDATE SHOPEE_H
	SET STATUS = 'CLOSE';
	COMMIT;
	end;
	begin
	UPDATE SHOPEE_D
	SET STATUS = 'CLOSE';
	INSERT INTO SHOPEE_KEEP_H(ORDERID, CU_WEB, AMOUNT, SDATE, TRANSFER, CU_NAME, PAYMENT, FEE_SERVICE, PAID_CU, CREATED_DATE, TRANS, STATUS, DISCAMT, BRANCH) 
	SELECT ORDERID, CU_WEB, AMOUNT, SDATE, TRANSFER, CU_NAME, PAYMENT, FEE_SERVICE, PAID_CU, CREATED_DATE, TRANS, STATUS, DISCAMT, BRANCH 
	FROM SHOPEE_H 
	WHERE ORDERID NOT IN (SELECT ORDERID FROM SHOPEE_KEEP_H) 
	AND STATUS = 'CLOSE';
	COMMIT;
	end;
	begin
	INSERT INTO SHOPEE_KEEP_D(ID, ORDERID, ITEM_CODE, QTY_A, PRICE, QTY, NET_PRICE, CREATED_DATE, OLD_PRICE, STATUS, BRANCH)
	SELECT ID, ORDERID, ITEM_CODE, QTY_A, PRICE, QTY, NET_PRICE, CREATED_DATE, OLD_PRICE, STATUS, BRANCH
	FROM SHOPEE_D
	WHERE ORDERID NOT IN (SELECT ORDERID FROM SHOPEE_KEEP_D) 
	AND STATUS = 'CLOSE';
	COMMIT;
	end;
END;