UPDATE SHOPEE_H
	SET CREATED_DATE = TRUNC(SYSDATE)--TO_DATE('17/06/2024','DD/MM/YYYY')
	WHERE TRUNC(CREATED_DATE) = TRUNC(SYSDATE);
	UPDATE SHOPEE_D
	SET CREATED_DATE = TRUNC(SYSDATE)--TO_DATE('17/06/2024','DD/MM/YYYY')
	WHERE TRUNC(CREATED_DATE) = TRUNC(SYSDATE);
	UPDATE SHOPEE_H
	SET ORDERID = TRIM(ORDERID),
				CU_WEB = TRIM(CU_WEB),
				AMOUNT = TRIM(AMOUNT),
					SDATE = TRIM(SDATE),
		TRANSFER = TRIM(TRANSFER),
			CU_NAME = TRIM(CU_NAME),
			PAYMENT = TRIM(PAYMENT);
	UPDATE SHOPEE_D
						SET ID = TRIM(ID),
			ORDERID = TRIM(ORDERID),
	ITEM_CODE = TRIM(ITEM_CODE),
					QTY_A = TRIM(QTY_A),
					PRICE = TRIM(PRICE),
							QTY = TRIM(QTY),
	NET_PRICE = TRIM(NET_PRICE);
	DELETE  SHOPEE_H WHERE (ORDERID) NOT IN (SELECT ORDERID FROM SHOPEE_NO) ;
	DELETE  SHOPEE_D WHERE (ORDERID) NOT IN (SELECT ORDERID FROM SHOPEE_NO) ;
	FOR X IN (SELECT A.ITEM_CODE 
                FROM SHOPEE_D A, INV_ITEM B
                WHERE A.ITEM_CODE = B.ITEM_CODE
                AND B.ITEM_STATUS = 'OBSOLETE') LOOP
       UPDATE INV_ITEM
       SET  ITEM_STATUS = 'ACTIVE'
       WHERE ITEM_CODE = X.ITEM_CODE;      
	END LOOP;           
	COMMIT;
	exception
     when no_data_found then
       null;